site_name: Toogethr integration
site_description: Documentation for the integration of Toogethr services
site_favicon: favicon.ico

# pages:
# - ['README.md', 'Introduction']
# - ['get-started/get-started.md', 'Get started', 'Get started']
# - ['get-started/understanding_groups.md', 'Get started', 'Understanding groups']
# - ['get-started/choose-tools-from-gallery.md', 'Get started', 'Choose tools from gallery']
# - ['get-started/tell-your-community.md', 'Get started', 'Tell your community']
# - ['documentation/documentation-overview.md', 'Documentation', 'Overview']
# - ['documentation/group-activities-widget.md', 'Documentation', 'Group activities widget']
# - ['documentation/group-rides-widget.md', 'Documentation', 'Group rides widget']
# - ['documentation/group-counter-widget.md', 'Documentation', 'Group counter widget']
# - ['documentation/facebook-page-tab-app.md', 'Documentation', 'Facebook page tab app']
# - ['toogethr-open-api/toogethr-open-api.md', 'Toogethr Open API', 'Toogethr Open API']
# - ['toogethr-open-api/examples.md', 'Toogethr Open API', 'Examples']
